### PR TITLE
[WIP] Refactor

### PR DESCRIPTION
**Pull request by LiorAgnin**

### CODE REVIEW

**Comment by LiorAgnin** [comment]
@SametSahin10 Feel free to propose any refactoring or improvements.

**Review by SametSahin10 — APPROVED** [review]
I've reviewed it briefly. Nice improvements! I'd never say no to renaming variables, classes to achieve better readability. I was not keen on the word "section". "module" is better.

**Comment by SametSahin10** [comment]
I've merged it. Could you publish a new version on pub.dev? @LiorAgnin

**Comment by LiorAgnin** [comment]
It's ok, I fixed it. I reopened the PR. @SametSahin10

**Pull request merged**
